### ISSUE TITLE
anti afk cannot detect roblox windows

### ISSUE THREAD

**Issue by russyboy1** [SpaceGT/Anti-AFK#10]
After i opened roblox and ran the script, it says no windows found. And i'll be kicked after 20 mins. How can i solve this? Thanks

**Comment by russyboy1** [comment]
![Screenshot_3](https://github.com/SpaceGT/Anti-AFK/assets/107330802/54403ce9-3306-49b3-b637-e4fe3b9a8042)

**Comment by SpaceGT** [comment]
Did you add your game into the config?

**Comment by russyboy1** [comment]
you mean the edit script function?

**Comment by russyboy1** [comment]
what you mean by config included in script

**Comment by russyboy1** [comment]
if i see "Monitoring: RobloxPlayerBeta.exe - 1" then is it working

**Comment by SpaceGT** [comment]
Sorry for the late response, I didn't get a ping.

> what you mean by config included in script

By "in the script" I meant opening it in a text editor. Everything is well-commented so you'll be fine from there.

> if i see "Monitoring: RobloxPlayerBeta.exe - 1" then is it working

Yes, if by "working" you mean waiting for the window to time out.
While it does see the window, it will wait for a bit of inactivity before it starts to send keypresses.
This should change to "Managing" once keystrokes are being sent.

A surprising amount of people have raised similar issues, where they haven't specified which processes to watch and are surprised when no windows are found.

When I get back from holiday, I'll update the README to be a bit more explicit in the matter and include instructions on how to find the config.
Hopefully this clears up the issue!

**Comment by russyboy1** [comment]
thanks for your response!
