### ISSUE TITLE
I got ERROR: Target windows not found.

### ISSUE THREAD

**Issue by DarealSimon** [SpaceGT/Anti-AFK#16]
The script worked perfectly for a while and then got This Error.
![Screenshot_1](https://github.com/SpaceGT/Anti-AFK/assets/90116696/eeced901-cdf1-4846-ac4e-52ef667e929b)
Make my Mouse and Keyboard doesn't work before I restart my computer.

**Comment by SpaceGT** [comment]
To clarify, you're using the latest version?

The reason this blocked input was the error prevented the script from executing the code used to restore control.
You may wish to disable input blocking while investigating this further.

**Comment by DarealSimon** [comment]
Yes, I used the latest version. Now disable BLOCK_INPUT and run for a day it's perfect. Thank!

**Comment by SpaceGT** [comment]
This has been fixed in b83201b7d4b54a3ecf35f6258d1a26a6e5861a48
