### ISSUE TITLE
Clarification on how to use the code properly

### ISSUE THREAD

**Issue by MMC-360** [SpaceGT/Anti-AFK#18]
So far the only changes I’ve made is adding “RobloxPlayerBeta.exe” to the PROCESS_LIST, is there any other change I need to do for this to prevent the afk kick on Roblox, and will this work with the window open or minimized? (I’m new to all of this so please be descriptive of any changes that may need to be made)

**Comment by SpaceGT** [comment]
>  adding “RobloxPlayerBeta.exe” to the PROCESS_LIST

That's correct.
By doing this, you've made sure Anti-AFK will monitor all windows relating to Roblox.

>  there any other change I need to do for this to prevent the afk kick on Roblox

Not that I'm aware of - if something broke and this no longer works please let me know.

> and will this work with the window open or minimized?

Yes, by "unfocused windows" the README is referring to windows that are minimized / in the background.

> I’m new to all of this so please be descriptive of any changes that may need to be made

By the looks of it, setting up Anti-AFK was easier then you thought! :D

**Comment by MMC-360** [comment]
I might reopen or comment if I find any issues but yeah it was simple and straightforward, thanks! :)
