### ISSUE TITLE
Does Roblox not minimize itself.

### ISSUE THREAD

**Issue by FurryDaniel** [SpaceGT/Anti-AFK#19]
Struggling to make it. I do not know why it give an error for missing anything function.

if that's possible to add https://www.autohotkey.com/docs/v2/lib/WinMinimize.htm

It'll save GPU less working on it.

**Comment by SpaceGT** [comment]
Since Roblox is relatively lightweight and usually CPU bottlenecked I can't imagine there'd be much performance gain.
Please let me know if your experience proves otherwise.

If you wish to add it yourself replace `WinMoveBottom` with `WinMinimize` in `resetTimer`.

**Comment by SpaceGT** [comment]
Any update on this?

**Comment by xXcalibre8** [comment]
hey man, I did all the instruction but for some reason it wouldn't work for me,

I was hoping to use it to AFK in PS99 while doing other stuff.
