### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by ISE9218** [SpaceGT/Anti-AFK#22]
Would this work if a laptop is in sleep mode or would it stop working?

**Comment by towermom9** [comment]
> Would this work if a laptop is in sleep mode or would it stop working?

Sleep on windows put all processes on halt and store them on ram.... Soo no it doesn't work when the laptop is on sleep mode, btw I highly recommend that you don't close the laptop while it's afk/hot cuz it might damage the screen.

**Comment by ISE9218** [comment]
Oh alright, thanks

**Comment by SpaceGT** [comment]
Glad this was sorted
