### ISSUE TITLE
Wrong AHK Version

### ISSUE THREAD

**Issue by russyboy1** [SpaceGT/Anti-AFK#7]
the latest release doesnt work
![圖片_2023-04-05_180311490](https://user-images.githubusercontent.com/107330802/230049142-cb5d6342-c22e-4c83-aad0-52c7bf9d8fc2.png)

**Comment by russyboy1** [comment]
![圖片_2023-04-05_180607508](https://user-images.githubusercontent.com/107330802/230049862-ad43ba1f-35d7-463c-bb51-c753833a2da8.png)

**Comment by russyboy1** [comment]
the previous version works fine

**Comment by SpaceGT** [comment]
Are you using AutoHotKey V2?

**Comment by russyboy1** [comment]
the latest

**Comment by russyboy1** [comment]
dk what version it is

**Comment by russyboy1** [comment]
a534954b86641524b27bc4c2a22a2706f2dff207

**Comment by SpaceGT** [comment]
Check the installation 'guide' in the ReadMe, [AutoHotKey](https://www.autohotkey.com/) has changed a lot since the previous version of the script was written.  

If you wish to use the latest version of the script you must update **AutoHotKey** to V2

**Comment by russyboy1** [comment]
kk
