### ISSUE TITLE
No windows found?

### ISSUE THREAD

**Issue by MystiaX** [SpaceGT/Anti-AFK#8]
It wont detect my game, I'm using AutoHotKey V2. It doesn't seem to be doing anything as well. I don't know if it's because I have two monitors running or what

**Comment by SpaceGT** [comment]
Did you add your game into the config?

**Comment by SpaceGT** [comment]
I'm closing this issue as invalid since it's not a problem with the script.
Glad everything worked out!

**Comment by Daxezy** [comment]
what config i dont know how to do it i have the same problem

**Comment by SpaceGT** [comment]
Open [Anti-AFK](https://github.com/SpaceGT/Anti-AFK/blob/master/Anti-AFK.ahk) in a text editor (once downloaded) and add the target process to the `PROCESS_LIST`.

**Comment by Daxezy** [comment]
I know, For example, this works for notepad.exe. But i want antiafk for roblox maybe do you know the roblox process name?

**Comment by SpaceGT** [comment]
You can figure it out with Window Spy, which is bundled with AutoHotkey.

Just search for `AutoHotkey Window Spy` in the Start Menu or right click on the SysTray icon of any AHK script.

Hover over the a window belonging to the process, you want its `ahk_exe` value.
