### ISSUE TITLE
Can't find target window

### ISSUE THREAD

**Issue by MystiaX** [SpaceGT/Anti-AFK#9]
Usually after a while of leaving it on I randomly get this error, I don't have anything else open either. It works perfectly fine for like 30-40 minutes or so but this pops up:

Error: Target window not found.

Specifically: A

	115: If (DenyInput && A_IsAdmin)
	116: BlockInput("On")
▶	118: oldWindow := WinGetID("A")
	120: WinSetTransparent(0, "ahk_id " targetWindow)
	121: WinActivate("ahk_id " targetWindow)

**Comment by SpaceGT** [comment]
I will look into it

**Comment by SpaceGT** [comment]
This should now be fixed in 14263d61f110720fa56cef555a57a64e91362fbb
